version: "3"

name: social-app

services:
  postgres:
    container_name: postgres
    build:
      context: social-app-backend
      dockerfile: Dockerfile.postgres
    ports:
      - "5432:5432"
  backend:
    container_name: backend
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/socialapp
    build:
      context: social-app-backend
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
  frontend:
    container_name: frontend
    depends_on:
      - backend
    build:
      context: social-app-frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "4200:80"
