version: "3"

services:
  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - "5432:5432"
  backend:
    container_name: backend
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/socialapp
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
