version: "3"

services:
  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - "5432:5432"
  backend:
    container_name: backend
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/socialapp
      - GOOGLE_CLIENT_ID=YourId
      - GOOGLE_CLIENT_SECRET=YourSecret
      - GITHUB_CLIENT_ID=YourID
      - GITHUB_CLIENT_SECRET=YourSecret
      - FRONTEND_URL=http://frontend:4200
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
