apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: social-app-backend
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/socialapp
            - name: GOOGLE_CLIENT_ID
              value: YourId
            - name: GOOGLE_CLIENT_SECRET
              value: YourSecret
            - name: GITHUB_CLIENT_ID
              value: YourID
            - name: GITHUB_CLIENT_SECRET
              value: YourSecret
            - name: FRONTEND_URL
              value: http://frontend-service:80
            - name: MAIL_HOST
              value: maildev-service
          dependsOn:
            - name: postgres-service
            - name: maildev-service
