apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: social-app-postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: socialapp
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: none
